### ISSUE TITLE
大佬 app_电信0点.py的瑞数通杀.js 文件有吗？

### ISSUE THREAD

**Issue by hwraul** [ywk1000/xmly_speed#3]
电信现在用了瑞数加密，没找到 app_电信0点.py 的瑞数通杀.js 文件，请问有吗？谢谢了

**Comment by hwraul** [comment]
看到 12月3号上传了一个瑞数通杀.js文件，但是跟app_电信0点.py或者app_电信凌晨3.py所需的参数不同，不能用

**Comment by ooojoker** [comment]
> 看到 12月3号上传了一个瑞数通杀.js文件，但是跟app_电信0点.py或者app_电信凌晨3.py所需的参数不同，不能用

找到木有？0点这个本也是没找到

**Comment by hwraul** [comment]
> > 看到 12月3号上传了一个瑞数通杀.js文件，但是跟app_电信0点.py或者app_电信凌晨3.py所需的参数不同，不能用
> 
> 找到木有？0点这个本也是没找到

换了别人修改的脚本，可以用了
